//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 09:13:26 PM CEST 
//


package localhost._8081.stats;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="users" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="messages" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "users",
    "messages",
    "comments"
})
@XmlRootElement(name = "getStatsResponse")
public class GetStatsResponse {

    protected long users;
    protected long messages;
    protected long comments;

    /**
     * Gets the value of the users property.
     * 
     */
    public long getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     */
    public void setUsers(long value) {
        this.users = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     */
    public long getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     */
    public void setMessages(long value) {
        this.messages = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     */
    public long getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     */
    public void setComments(long value) {
        this.comments = value;
    }

}
